/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.app.view;

import com.app.util.Temperature;
import com.app.util.Unit;
import java.awt.event.KeyEvent;

/**
 *
 * @author josef
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        buttonGroup1.add(radioOption1);
        buttonGroup1.add(radioOption2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        fieldValue = new javax.swing.JTextField();
        comboOptions = new javax.swing.JComboBox<>();
        radioOption1 = new javax.swing.JRadioButton();
        radioOption2 = new javax.swing.JRadioButton();
        buttonCalculate = new javax.swing.JButton();
        labelResult = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("> Conversor de Temperatura <");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        fieldValue.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        fieldValue.setText("0");
        fieldValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldValueActionPerformed(evt);
            }
        });
        fieldValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldValueKeyReleased(evt);
            }
        });

        comboOptions.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        comboOptions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "º C", "º F", "º K" }));
        comboOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboOptionsActionPerformed(evt);
            }
        });

        radioOption1.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        radioOption1.setSelected(true);
        radioOption1.setText("A Fahrenheit");
        radioOption1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioOption1ActionPerformed(evt);
            }
        });

        radioOption2.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        radioOption2.setText("A Kelvin");
        radioOption2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioOption2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(fieldValue, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboOptions, 0, 104, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(radioOption1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radioOption2)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioOption1)
                    .addComponent(radioOption2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonCalculate.setText("Calcular");
        buttonCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCalculateActionPerformed(evt);
            }
        });

        labelResult.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        labelResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonCalculate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelResult, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCalculateActionPerformed
        calculo();
    }//GEN-LAST:event_buttonCalculateActionPerformed

    private void comboOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboOptionsActionPerformed

        switch (comboOptions.getSelectedIndex()) {
            case 0:
                radioOption1.setText(Unit.TO_FAHRENHEIT);
                radioOption2.setText(Unit.TO_KELVIN);
                break;
            case 1:
                radioOption1.setText(Unit.TO_CELSIUS);
                radioOption2.setText(Unit.TO_KELVIN);
                break;
            case 2:
                radioOption1.setText(Unit.TO_CELSIUS);
                radioOption2.setText(Unit.TO_FAHRENHEIT);
        }
        buttonCalculateActionPerformed(evt);
    }//GEN-LAST:event_comboOptionsActionPerformed

    private void radioOption1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioOption1ActionPerformed
        buttonCalculateActionPerformed(evt);
    }//GEN-LAST:event_radioOption1ActionPerformed

    private void radioOption2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioOption2ActionPerformed
        buttonCalculateActionPerformed(evt);
    }//GEN-LAST:event_radioOption2ActionPerformed

    private void fieldValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldValueActionPerformed
        buttonCalculateActionPerformed(evt);
    }//GEN-LAST:event_fieldValueActionPerformed

    private void fieldValueKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldValueKeyReleased
        calculo();
    }//GEN-LAST:event_fieldValueKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCalculate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboOptions;
    private javax.swing.JTextField fieldValue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelResult;
    private javax.swing.JRadioButton radioOption1;
    private javax.swing.JRadioButton radioOption2;
    // End of variables declaration//GEN-END:variables

    private void calculo() {
        String result = fieldValue.getText();
        if(result.isEmpty()){
            result = "0";
            fieldValue.setText("0");
        }
        double r = Double.parseDouble(result);
        String unit = "";

        switch (comboOptions.getSelectedIndex()) {
            case 0://Celsius
                if (radioOption1.isSelected()) {
                    r = Temperature.celsiusToFahrenheit(r);
                    unit = Unit.FAHRENHEIT;
                } else {
                    r = Temperature.celsiusToKelvin(r);
                    unit = Unit.KELVIN;
                }
                break;
            case 1://Fahrenheit
                if (radioOption1.isSelected()) {
                    r = Temperature.fahrenheitToCelsius(r);
                    unit = Unit.CELSIUS;
                } else {
                    r = Temperature.fahrenheitToKelvin(r);
                    unit = Unit.KELVIN;
                }
                break;
            case 2://kelvin
                if (radioOption1.isSelected()) {
                    r = Temperature.kelvinToCelsius(r);
                    unit = Unit.CELSIUS;
                } else {
                    r = Temperature.kelvinToFahrenheit(r);
                    unit = Unit.FAHRENHEIT;
                }
                break;
        }

        labelResult.setText(String.format("%.2f %s", r, unit));
    }
}
