/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import lib.OhmLaw;

/**
 *
 * @author josef
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setButtonGroup();
    }

    private void setButtonGroup() {
        buttonGroup1.add(radioCurrent);
        buttonGroup1.add(radioVoltage);
        buttonGroup1.add(radioResistanse);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        radioVoltage = new javax.swing.JRadioButton();
        radioResistanse = new javax.swing.JRadioButton();
        radioCurrent = new javax.swing.JRadioButton();
        labelOne = new javax.swing.JLabel();
        fieldOne = new javax.swing.JTextField();
        labelUnitOne = new javax.swing.JLabel();
        labelTwo = new javax.swing.JLabel();
        fieldTwo = new javax.swing.JTextField();
        labelUnitTwo = new javax.swing.JLabel();
        buttonCalculate = new javax.swing.JButton();
        fieldResult = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ley de Ohm");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Calcualdora Ley de Ohm");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "¿Qué desea calcular?"));

        radioVoltage.setSelected(true);
        radioVoltage.setText("Voltaje");
        radioVoltage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVoltageActionPerformed(evt);
            }
        });

        radioResistanse.setText("Resistencia");
        radioResistanse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioResistanseActionPerformed(evt);
            }
        });

        radioCurrent.setText("Corriente");
        radioCurrent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCurrentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioVoltage)
                .addGap(18, 18, 18)
                .addComponent(radioCurrent)
                .addGap(18, 18, 18)
                .addComponent(radioResistanse)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioVoltage)
                    .addComponent(radioCurrent)
                    .addComponent(radioResistanse))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelOne.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        labelOne.setText("Corriente");

        fieldOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldOneActionPerformed(evt);
            }
        });

        labelUnitOne.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        labelUnitOne.setText("A");

        labelTwo.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        labelTwo.setText("Resistencia");

        fieldTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldTwoActionPerformed(evt);
            }
        });

        labelUnitTwo.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        labelUnitTwo.setText("Ω");

        buttonCalculate.setText("Calcular");
        buttonCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCalculateActionPerformed(evt);
            }
        });

        fieldResult.setEditable(false);
        fieldResult.setBackground(new java.awt.Color(238, 238, 238));
        fieldResult.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        fieldResult.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldResult.setText("resultado");
        fieldResult.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fieldResult, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonCalculate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelOne)
                                        .addGap(18, 18, 18)
                                        .addComponent(fieldOne))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(labelTwo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fieldTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelUnitTwo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelUnitOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelOne)
                    .addComponent(fieldOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUnitOne))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTwo)
                    .addComponent(fieldTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUnitTwo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCalculate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldResult, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCalculateActionPerformed
        calculate();
    }//GEN-LAST:event_buttonCalculateActionPerformed

    private void radioVoltageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVoltageActionPerformed
        setLabels(
                new String[]{OhmLaw.CURRENT, OhmLaw.RESISTANCE},
                new String[]{OhmLaw.UNIT_AMPER, OhmLaw.UNIT_RESISTANCE}
        );
        calculate();
    }//GEN-LAST:event_radioVoltageActionPerformed

    private void radioCurrentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCurrentActionPerformed
        setLabels(
                new String[]{OhmLaw.VOLTAGE, OhmLaw.RESISTANCE},
                new String[]{OhmLaw.UNIT_VOLTAGE, OhmLaw.UNIT_RESISTANCE}
        );
        calculate();
    }//GEN-LAST:event_radioCurrentActionPerformed

    private void radioResistanseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioResistanseActionPerformed
        setLabels(
                new String[]{OhmLaw.VOLTAGE, OhmLaw.CURRENT},
                new String[]{OhmLaw.UNIT_VOLTAGE, OhmLaw.UNIT_AMPER}
        );
        calculate();
    }//GEN-LAST:event_radioResistanseActionPerformed

    private void fieldOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldOneActionPerformed
        calculate();
    }//GEN-LAST:event_fieldOneActionPerformed

    private void fieldTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldTwoActionPerformed
        calculate();
    }//GEN-LAST:event_fieldTwoActionPerformed

    private void setLabels(String[] names, String[] units) {
        labelOne.setText(names[0]);
        labelTwo.setText(names[1]);

        labelUnitOne.setText(units[0]);
        labelUnitTwo.setText(units[1]);
    }

    private void calculate() {
        if (isValidateFields(fieldOne) && isValidateFields(fieldTwo)) {
            if (radioVoltage.isSelected()) {
                String valor1 = fieldOne.getText();
                double current = Double.parseDouble(valor1);

                String valor2 = fieldTwo.getText();
                double resistance = Double.parseDouble(valor2);

                double result = OhmLaw.calculateVoltage(current, resistance);

                fieldResult.setText(String.format("%.2f %s", result, OhmLaw.UNIT_VOLTAGE));
            } else if (radioCurrent.isSelected()) {
                String valor1 = fieldOne.getText();
                double voltage = Double.parseDouble(valor1);

                String valor2 = fieldTwo.getText();
                double resistance = Double.parseDouble(valor2);

                double result = OhmLaw.calculateCurrent(voltage, resistance);

                fieldResult.setText(String.format("%.2f %s", result, OhmLaw.UNIT_AMPER));
            } else if (radioResistanse.isSelected()) {
                String valor1 = fieldOne.getText();
                double voltage = Double.parseDouble(valor1);

                String valor2 = fieldTwo.getText();
                double current = Double.parseDouble(valor2);

                double result = OhmLaw.calculateResistance(voltage, current);

                fieldResult.setText(String.format("%.2f %s", result, OhmLaw.UNIT_RESISTANCE));
            }
        }

    }

    private boolean isValidateFields(JTextField field) {
        boolean result = true;

        if (field.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Está vacío");
            result = false;
        } else {
            try {
                String content = field.getText();
                Double.parseDouble(content);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Solo digitos");
                result = false;
            }
        }

        return result;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCalculate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField fieldOne;
    private javax.swing.JTextField fieldResult;
    private javax.swing.JTextField fieldTwo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelOne;
    private javax.swing.JLabel labelTwo;
    private javax.swing.JLabel labelUnitOne;
    private javax.swing.JLabel labelUnitTwo;
    private javax.swing.JRadioButton radioCurrent;
    private javax.swing.JRadioButton radioResistanse;
    private javax.swing.JRadioButton radioVoltage;
    // End of variables declaration//GEN-END:variables
}
